esphome:
  name: "apollo-temp-pro-1-eth"
  friendly_name: Apollo TEMP_PRO-1 ETH
  comment: Apollo TEMP_PRO-1 ETH
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.TEMP_PRO-1-ETH"
    version: "${version}"

  min_version: 2025.2.0

dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP_PROJECT-1/Integrations/ESPHome/TEMP_PRO-1_ETH.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://apolloautomation.github.io/TEMP_PROJECT-1/firmware-e/manifest.json

logger:

ethernet:  
  type: W5500  
  clk_pin: GPIO10  
  mosi_pin: GPIO12 
  miso_pin: GPIO11
  cs_pin: GPIO9
  interrupt_pin: GPIO13
  reset_pin: GPIO14

script:
  - id: statusCheck
    then:
      - if:
          condition:
            - lambda: 'return id(ink_ha_connected).state;'
          then:
            - logger.log: "Apollo Automation: Connected To HA"
            - light.turn_on: 
                id: rgb_light
                brightness: 100%
                red: 0%
                green: 0%
                blue: 100%
      - delay: 5s
      - light.turn_off: rgb_light

packages:
  core: !include Core.yaml
