name: Publish
env:
  DEVICE_NAME: temp-pro-1

on:
  push:
    branches:
      - main

jobs:
  check-for-yaml:
    name: Check for YAML Changes
    runs-on: ubuntu-latest
    outputs:
      yaml_changed: ${{ steps.check.outputs.yaml_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find .yaml Changes in Last PR Merge
        id: check
        run: |
          BASE_COMMIT=$(git rev-parse HEAD^1)
          MERGE_COMMIT=$(git rev-parse HEAD)
          if git diff --name-only $BASE_COMMIT $MERGE_COMMIT | grep -q '\.yaml$'; then
            echo "yaml_changed=true" >> $GITHUB_OUTPUT
          else
            echo "yaml_changed=false" >> $GITHUB_OUTPUT

  set-version:
    name: Set Version
    runs-on: ubuntu-latest
    needs: [check-for-yaml]
    if: needs.check-for-yaml.outputs.yaml_changed == 'true'
    outputs:
      version: ${{ steps.read_version.outputs.version }}
      upload_url: ${{ steps.run-release-drafter.outputs.upload_url }}
      html_url: ${{ steps.run-release-drafter.outputs.html_url }}
      # removed 'body' to avoid environment truncation
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from YAML file
        id: read_version
        run: |
          version=$(awk '/substitutions:/ {found=1} found && /version:/ {print $2; exit}' Integrations/ESPHome/Core.yaml | tr -d '"')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Detected version: $version"

      - name: 🚀 Run Release Drafter
        id: run-release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.read_version.outputs.version }}
          publish: true
          tag: ${{ steps.read_version.outputs.version }}
          name: Release ${{ steps.read_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 1) Fetch the final release body from GH API
      - name: Fetch Final Release Drafter Body
        id: fetch_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ steps.read_version.outputs.version }}"
          release_json=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/$tag")
          final_body=$(echo "$release_json" | jq -r '.body')
          echo "$final_body" > final_release_body.txt

      # 2) Upload that body as an artifact (no step output => no truncation)
      - name: Upload Release Body Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-body
          path: final_release_body.txt

  build-firmware-e:
    name: Build And Release (Firmware E)
    needs:
      - check-for-yaml
      - set-version
    if: needs.check-for-yaml.outputs.yaml_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Final Body
        uses: actions/download-artifact@v4
        with:
          name: release-body
          path: .

      - name: Call ESPHome Reusable Workflow
        uses: esphome/workflows/.github/workflows/build.yml@main
        with:
          files: |
            Integrations/ESPHome/TEMP_PRO-1_ETH.yaml
          esphome-version: stable
          combined-name: firmware-e
          summary-file: final_release_body.txt  # <--- pass the file directly
          release-version: ${{ needs.set-version.outputs.version }}

  build-firmware-w:
    name: Build And Release (Firmware W)
    needs:
      - check-for-yaml
      - set-version
    if: needs.check-for-yaml.outputs.yaml_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Final Body
        uses: actions/download-artifact@v4
        with:
          name: release-body
          path: .

      - name: Call ESPHome Reusable Workflow
        uses: esphome/workflows/.github/workflows/build.yml@main
        with:
          files: |
            Integrations/ESPHome/TEMP_PRO-1_W.yaml
          esphome-version: stable
          combined-name: firmware-w
          summary-file: final_release_body.txt
          release-url: ${{ needs.set-version.outputs.html_url }}
          release-version: ${{ needs.set-version.outputs.version }}

  build-site:
    name: Build Site
    runs-on: ubuntu-latest
    needs:
      - build-firmware-e
      - build-firmware-w
      - set-version
    if: needs.check-for-yaml.outputs.yaml_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./static
          destination: ./output

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: output

  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build-site
      - build-firmware-e
      - build-firmware-w
      - set-version
    if: needs.check-for-yaml.outputs.yaml_changed == 'true' && ${{ github.run_attempt == 1 }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: firmware-e
          path: firmware-e

      - uses: actions/download-artifact@v4
        with:
          name: firmware-w
          path: firmware-w

      - name: Zip firmware
        run: |
          zip -r firmware-e.zip firmware-e
          zip -r firmware-w.zip firmware-w

      - name: Upload firmware-e.zip
        id: upload-firmware
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.set-version.outputs.upload_url }}
          asset_path: firmware-e.zip
          asset_name: firmware-e.zip
          asset_content_type: application/zip

      - name: Upload firmware-w.zip
        id: upload-firmware-w
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.set-version.outputs.upload_url }}
          asset_path: firmware-w.zip
          asset_name: firmware-w.zip
          asset_content_type: application/zip

      - name: Copy firmware-e
        run: |
          mkdir -p output/firmware-e
          cp -r firmware-e/${{ needs.build-firmware-e.outputs.version }}/* output/firmware-e/

      - name: Copy firmware-w
        run: |
          mkdir -p output/firmware-w
          cp -r firmware-w/${{ needs.build-firmware-w.outputs.version }}/* output/firmware-w/

      - uses: actions/download-artifact@v4
        with:
          name: site
          path: output

      - uses: actions/upload-pages-artifact@v3
        with:
          path: output
          retention-days: 1

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4