name: CI

on:
  pull_request:

permissions:
  # Allow GITHUB_TOKEN to add labels to pull requests
  pull-requests: write
  issues: write
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  label-check:
    uses: ApolloAutomation/Workflows/.github/workflows/label-check.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
  ci:
    needs: [ label-check ]
    strategy:
      fail-fast: false
      matrix:
        esphome-version:
          - stable
          - beta
          - dev
    uses: ApolloAutomation/Workflows/.github/workflows/build.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
    with:
      device-name: temp-project-1
      yaml-files: |
        Integrations/ESPHome/TEMP_PRO-1_ETH.yaml
        Integrations/ESPHome/TEMP_PRO-1_W.yaml
      esphome-version: ${{ matrix.esphome-version }}
